/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HubitusCheckupService } from "../hubitusCheckup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HubitusCheckupCreateInput } from "./HubitusCheckupCreateInput";
import { HubitusCheckupWhereInput } from "./HubitusCheckupWhereInput";
import { HubitusCheckupWhereUniqueInput } from "./HubitusCheckupWhereUniqueInput";
import { HubitusCheckupFindManyArgs } from "./HubitusCheckupFindManyArgs";
import { HubitusCheckupUpdateInput } from "./HubitusCheckupUpdateInput";
import { HubitusCheckup } from "./HubitusCheckup";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HubitusCheckupControllerBase {
  constructor(
    protected readonly service: HubitusCheckupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HubitusCheckup })
  @nestAccessControl.UseRoles({
    resource: "HubitusCheckup",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: HubitusCheckupCreateInput
  ): Promise<HubitusCheckup> {
    return await this.service.create({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        testTime: true,
        currentHabitus: true,
        testResult: true,
        countResult: true,
        suggest: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HubitusCheckup] })
  @ApiNestedQuery(HubitusCheckupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HubitusCheckup",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<HubitusCheckup[]> {
    const args = plainToClass(HubitusCheckupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        testTime: true,
        currentHabitus: true,
        testResult: true,
        countResult: true,
        suggest: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HubitusCheckup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HubitusCheckup",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: HubitusCheckupWhereUniqueInput
  ): Promise<HubitusCheckup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        testTime: true,
        currentHabitus: true,
        testResult: true,
        countResult: true,
        suggest: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HubitusCheckup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HubitusCheckup",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: HubitusCheckupWhereUniqueInput,
    @common.Body() data: HubitusCheckupUpdateInput
  ): Promise<HubitusCheckup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          testTime: true,
          currentHabitus: true,
          testResult: true,
          countResult: true,
          suggest: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HubitusCheckup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HubitusCheckup",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: HubitusCheckupWhereUniqueInput
  ): Promise<HubitusCheckup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          testTime: true,
          currentHabitus: true,
          testResult: true,
          countResult: true,
          suggest: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
